openapi: '3.0.2'
info:
  title: API Title
  description: Address API
  version: '1.0'
servers:
  - url: http://localhost:8000
paths:
  /api/contacts/{idContact}/addresses:
    post:
      description: Create new address
      parameters:
        - name: Authorization
          schema:
            type: string
          in: header
        - name: idContact
          schema:
            type: number
          required: true
          in: path
      requestBody:
        description: Create new address
        content:
          application/json:
            schema:
              type: object
              properties:
                street:
                  type: string
                city:
                  type: string
                provice:
                  type: string
                country:
                  type: string
                postal_code:
                  type: string
      responses:
        201:
          description: Success create address
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: number
                      street:
                        type: string
                      city:
                        type: string
                      provice:
                        type: string
                      country:
                        type: string
                      postal_code:
                        type: string
                  errors:
                    type: object
    get:
      description: Get list addresses
      parameters:
      - name: Authorization
        schema:
          type: string
        in: header
      - name: idContact
        schema:
          type: number
        required: true
        in: path
      responses:
        200:
          description: List addresses
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                        street:
                          type: string
                        city:
                          type: string
                        provice:
                          type: string
                        country:
                          type: string
                        postal_code:
                          type: string
                  errors:
                    type: object
  /api/contacts/{idContact}/addresses/{idAddress}:
    get:
      description: Get address
      parameters:
        - name: Authorization
          schema:
            type: string
          in: header
        - name: idContact
          schema:
            type: number
          in: path
          required: true
        - name: idAddress
          schema:
            type: number
          in: path
          required: true
      responses:
        200:
          description: Success get address
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: number
                      street:
                        type: string
                      city:
                        type: string
                      provice:
                        type: string
                      country:
                        type: string
                      postal_code:
                        type: string
                  errors:
                    type: object
    put:
      description: Update address
      parameters:
          - name: Authorization
            schema:
              type: string
            in: header
          - name: idContact
            schema:
              type: number
            in: path
            required: true
          - name: idAddress
            schema:
              type: number
            in: path
            required: true
      requestBody:
        description: Update existing contact address
        content:
          application/json:
            schema:
              type: object
              properties:
                street:
                  type: string
                city:
                  type: string
                provice:
                  type: string
                country:
                  type: string
                postal_code:
                  type: string
      responses:
        200:
          description: Success create address
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: number
                      street:
                        type: string
                      city:
                        type: string
                      provice:
                        type: string
                      country:
                        type: string
                      postal_code:
                        type: string
                  errors:
                    type: object
    delete:
      description: Delete address
      parameters:
          - name: Authorization
            schema:
              type: string
            in: header
          - name: idContact
            schema:
              type: number
            in: path
            required: true
          - name: idAddress
            schema:
              type: number
            in: path
            required: true
      responses:
        200:
          description: Success delete address
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: boolean
                  errors:
                    type: object
